--- 
after_script: 
  - "php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml"
before_script: 
  - "wget https://scrutinizer-ci.com/ocular.phar"
language: php
php: 
  - 5.6
  - 5.5
  - 5.4
  - hhvm
script: 
  - "phpunit --bootstrap Kmom07/test/config.php --coverage-clover coverage.clover test"
  - "phpunit --bootstrap Kmom07/vendor/mos/cdatabase/test/config.php --coverage-clover coverage.clover test"
  - "phpunit --bootstrap Kmom07/vendor/mos/cform/test/config.php --coverage-clover coverage.clover test"




